### ISSUE TITLE
password database files

### ISSUE THREAD

**Issue by huangsijun17** [ElCholoGamer/userlogin#38]
I want to be able to share the password with the 1.7.10 login plugin. Is it possible to share the password database with the AuthME plugin?

**Comment by Grazen0** [comment]
**Sharing** is most likely not possible, due to the differences in how AuthMe and UserLogin structure their saved data.
**Migrating**, on the other hand, is most likely possible.

I see AuthMe has an option for [bcrypt](https://github.com/patrickfav/bcrypt)-hashed passwords. You'd have to turn it on first and foremost, as UserLogin also stores its passwords bycrpt-hashed.

I'm not sure how the structure for AuthMe's saved data works, but you'd probably have to restructure UserLogin's `playerData.yml` for it to be compatible with AuthMe afterwards.

**Comment by Grazen0** [comment]
Alright, I'll close this due to inactivity.
